---

- name: install fluent-bit
  apt:
    name: fluent-bit
    update_cache: yes

- name: copy config
  template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf

- name: run service
  systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: fluent-bit.service
