---
# tasks file for promtail
- name: create user
  user:
    name: promtail
    system: true
    group: adm

- name: create dir
  file:
    path: /etc/promtail
    state: directory
    owner: promtail
    group: adm

- name: copy config
  template:
    src: config-promtail.yml.j2
    dest: /etc/promtail/config-promtail.yml
  notify:
    - Restart Promtail

- name: copy systemd unit
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
  notify:
    - Restart Promtail

- name: download
  get_url:
    url: https://github.com/grafana/loki/releases/download/v2.4.1/promtail-linux-amd64.zip
    dest: /usr/bin/promtail-linux-amd64.zip

- name: install packes
  apt:
    name: unzip
    update_cache: yes

- name: unzip
  unarchive:
    src: /usr/bin/promtail-linux-amd64.zip
    dest: /usr/bin
    remote_src: yes
    owner: promtail
    group: adm
    mode: a+x
  notify:
    - Restart Promtail



