all:
  hosts:
    prometheus:
      ansible_host: IP host_1 #указать IP hosta
    node01_service:
      ansible_host: IP host_2 #указать IP hosta
    node02_prod:
      ansible_host: IP host_3 #указать IP hosta

monitoring:
  hosts:
    prometheus:

node_exporter:
  hosts:
    node01_service:
    node02_prod:

prod:
  hosts:
    node02_prod:

nginx:
  hosts:
    node01_service:

promtail:
  hosts:
    prometheus:
    node01_service:
    node02_prod:

loki:
  hosts:
    node01_service:

consul:
  hosts:
    prometheus:
    node01_service:
    node02_prod:

