---
# tasks file for consul_service_registry

- name: Copy service
  template: 
    src: consul-registry.service.j2
    dest: /etc/systemd/system/consul-registry.service

- name: Run service
  systemd: 
    state: started
    daemon_reload: true
    enabled: true
    name: consul-registry  

